theme: jekyll-theme-slate
theme: texture

texture:
  title: Peiman Shokouhian
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  social_links:
    twitter:
    github: peimansh
    linkedIn:
